version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.2

executors:
  default:
    docker:
      - image: circleci/node:16-browsers

workflows:
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master

commands:
  deploy:
    steps:
      - run: npm run deploy
  setup:
    steps:
      - checkout
      - aws-cli/install
      - aws-cli/setup
      - run: npm install

jobs:
  deploy:
    executor:
      name: default
    steps:
      - setup
      - deploy
